version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container_smartmentoring
    environment:
      - POSTGRESQL_USERNAME=smartmentoring
      - POSTGRESQL_PASSWORD=smartmentoring@2025
      - POSTGRESQL_DATABASE=smartmentoring_api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
