version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container_quoth
    environment:
      - POSTGRESQL_USERNAME=quoth
      - POSTGRESQL_PASSWORD=quoth@2024
      - POSTGRESQL_DATABASE=quoth_api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
